require: rubocop-rails
require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions:
    rubocop-rake: true
    rubocop-rails: true
  Exclude:
    - 'bin/bundle'

Style/Documentation:
  Enabled: false
